<?xml version="1.0"?>
<package format="2">
  <name>subt_planner</name>
  <version>0.0.0</version>
  <description>Subterranean autonomous exploration planner based on spatial cognitive maps</description>
  <maintainer email="ggh@subtplanner.dev">SubtPlanner Developers</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>catkin</buildtool_depend>
  <buildtool_depend>catkin_simple</buildtool_depend>
  <depend>roscpp</depend>
  <depend>cv_bridge</depend>
  <depend>tf</depend>
  <depend>message_generation</depend>
  <depend>geometry_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>kdtree</depend>
  <depend>cognitive_graph_model</depend>
  <depend>voxel_map</depend>
  <depend>local_exploration</depend>
  <depend>planner_msgs</depend>
  <depend>planner_semantic_msgs</depend>
  <depend>global_repositioning</depend>
  <depend>pcl_ros</depend>
  <depend>behaviortree_cpp</depend>
  <depend>roslib</depend>
  
</package>
